name: Update Spheron Cluster Instance
 
on:
  push:
    branches:
      - main
 
jobs:
  update-spheron-instance:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout repository
        id: checkout-repository
        uses: actions/checkout@v3
 
      - name: Extract version
        id: extract-version
        run: echo "version=$(cat package.json | jq -r '.version')" >> "$GITHUB_OUTPUT"
 
      - name: Login to Docker Hub
        id: docker-hub-login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
 
      - name: Set up Docker Buildx
        id: docker-buildx-setup
        uses: docker/setup-buildx-action@v2
 
      - name: Build and push
        id: docker-build-n-push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: vezga/waslah:${{ steps.extract-version.outputs.version }}
 
      - name: Update Spheron Instance
        id: update-spheron-instance
        uses: spheronFdn/instance-update-action@v1.0.0
        with:
          spheron-token: ${{ secrets.SPHERON_TOKEN }}
          instance-id: ${{ secrets.SPHERON_INSTANCE_ID }}
          tag: ${{ steps.extract-version.outputs.version }}
          env: '[ "key1=value1", "key2=value2" ]'
          secret-env: '[ "skey1=svalue1", "skey2=svalue2" ]'